
services:
  voting-app:
    build: ./voting-app
    ports:
      - "5000:80"
    env_file:
      - ./.env
    networks:
      - voting-net
    depends_on:
      - redis

  result-app:
    build: ./result-app
    ports:
      - "5001:80"
    env_file:
      - ./.env
    networks:
      - voting-net
    depends_on:
      - db

  worker:
    build: ./worker
    env_file:
      - ./.env
    networks:
      - voting-net
    depends_on:
      - redis
      - db

  redis:
    image: "redis:7-alpine"
    ports:
        - "${REDIS_PORT}:6379"
    networks:
      - voting-net
    volumes:
      - redis-data:/data

  db:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - voting-net
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  voting-net:
    driver: bridge

volumes:
  db-data:
  redis-data: