apiVersion: v1
kind: ConfigMap
metadata:
  name: db-initdb-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS votes (
      id VARCHAR(255) NOT NULL UNIQUE,
      vote VARCHAR(255) NOT NULL
    );
