apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: voting-app
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: voting-app
    tier: db