apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
    tier: frontend