apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
      tier: frontend
  template:
    metadata:
      labels:
        app: voting-app
        tier: frontend
    spec:
      containers:
        - name: voting-app
          image: gimmeursocks/devops-monitoring-voting-app:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-service
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
